### ISSUE TITLE
tmux: when switching background color with select-pane -P, color is lost with new lines

### ISSUE THREAD

**Issue by mattsawyer77** [jwilm/alacritty#1191]
Which operating system does the issue occur on?
macOS 10.13.3, with tmux 2.6

steps to reproduce: 
1. open a tmux session
2. press the tmux prefix key, then `:select-pane -P 'bg=red'` (at this point the background of the tmux pane should be red)
3. run a command that has multiple lines of output (e.g. `ls -la`)

results:
the background color after the newline character of each line is not red but the original background color

expected:
the background color should be applied to the whitespace at the end of the line

This works as expected in iTerm 3.1.5.

**Comment by sodiumjoe** [comment]
are you on latest master? I can't repro, also on tmux 2.6 and macOS 10.13.4.

**Comment by mattsawyer77** [comment]
Sorry, I just remembered I was on the scrollback branch.

**Comment by jwilm** [comment]
This should be fixed on the latest scrollback branch. Can you verify @mattsawyer77?

**Comment by mattsawyer77** [comment]
I just pulled the latest from the scrollback branch and re-built, re-installed. But I still see the issue. When I first change the background color, the whole background is the new color. But once I start hitting enter or entering a command (e.g. `ls -la`) the background after the newline character is reset back to the default. In other words, the background of the characters printed are correct but not the remaining whitespace of the line.

**Comment by jwilm** [comment]
Ok that's surprising. I'll look into it. Thanks for the report!

**Comment by jwilm** [comment]
Was this a problem for you on master?

**Comment by fehrnah** [comment]
I have a similar problem. On (neo)vim, when scrolling (withing vim), the background color goes to black.

**Comment by mattsawyer77** [comment]
I just switched back to master, pulled, and rebuilt (doing `cargo build --release`). I still see the issue. Perhaps there is something I'm missing here re: building or perhaps there is something amiss in my configuration?

**Comment by jwilm** [comment]
@mattsawyer77 After rebuilding, are you running the binary dropped into `target/release/alacritty`?

**Comment by mattsawyer77** [comment]
OK I see the problem now. I was coping the Alacrity.app to my /Applications folder and running it that way. When I invoke alacritty from iTerm via `./target/release/alacritty` I do not see the problem in either the master or scrollback branches.
