### ISSUE TITLE
tmux in Alacritty

### ISSUE THREAD

**Issue by freevova** [jwilm/alacritty#1401]
MacBook Pro (Retina, 13-inch, Late 2013)

I have the issue with tmux integration. It works fine for iterm2 but it doesn't for alacritty.

**Comment by freevova** [comment]
<img width="1680" alt="screen shot 2018-06-30 at 5 56 23 pm" src="https://user-images.githubusercontent.com/15907211/42126325-4ca6f418-7c8f-11e8-9e91-774a13f7004e.png">
<img width="1492" alt="screen shot 2018-06-30 at 5 56 51 pm" src="https://user-images.githubusercontent.com/15907211/42126328-52115a4c-7c8f-11e8-949b-9c14d4208873.png">

**Comment by freevova** [comment]
It was because of wrong tmux configs 😞

**Comment by freevova** [comment]
It was because of wrong tmux configs 😞

**Comment by voider1** [comment]
@freevova Did it used to work before? Because my entire config used to just wokr.

**Comment by freevova** [comment]
I am reopening current issue. @voider1 Yes it worked at the very beginning. Then it crashed during my work. I don't know if it is related to configuration files, because even after reinstalling alactricitty and `cleaning` my config,  Powerline fonts don't work too

**Comment by chrisduerr** [comment]
@freevova Did alacritty crash or tmux? Are you running the latest master version?

**Comment by freevova** [comment]
@chrisduerr It is tmux crash, because it works fine without tmux. And yes, I use the lates master version.
Without tmux:
![screen shot 2018-07-02 at 11 30 20 am 2](https://user-images.githubusercontent.com/15907211/42153303-65bdb984-7deb-11e8-8c54-51c8558ea1d7.png)
With tmux:
![screen shot 2018-07-02 at 11 30 46 am 2](https://user-images.githubusercontent.com/15907211/42153331-775cca18-7deb-11e8-88cd-aaf15735bdb8.png)

**Comment by h-michael** [comment]
@freevova 
Could you show us your alacritty and tmux config ?

**Comment by xordspar0** [comment]
I have this issue, too. tmux on its own seems to be fine, but when I configure it with powerline, the status line gets duplicated every time its contents change.

Here's my tmux config:
```tmux
set-option -g default-shell "/usr/local/bin/fish"
set-option -g history-limit 10000
set-option -g mouse on

# Switch copy mode to use vim-style keybindings.
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection
bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down

# Turn on powerline.
run-shell "powerline-daemon -q"
source "/path/to/powerline.conf"
set-option -g status-left-length 90
set-option -g status-right-length 60
```

And here's `powerline.conf`: https://github.com/powerline/powerline/blob/develop/powerline/bindings/tmux/powerline.conf

That's the entry point to Powerline, so it runs some more complicated scripts. It seems to end up at [powerline/bindings/config.py](https://github.com/powerline/powerline/blob/develop/powerline/bindings/config.py).

**Comment by xordspar0** [comment]
Here's a demonstration of the bug:

![alacritty-tmux-powerline](https://user-images.githubusercontent.com/2390950/42177412-4a29ff64-7df2-11e8-916b-29b63f5ba733.gif)

1. The time changes, updating the text of the status line, causing the first duplicate line.
2. I change the directory, with similar results.
3. I change into a git directory, which adds the branch info to the status line, causing a third duplicate line.

**Comment by voider1** [comment]
@xordspar0 I fixed my issues by setting the right locale. Could you show your locale?

**Comment by xordspar0** [comment]
`LANG` and `LC_ALL` are set to `en_US.UTF-8`. Starting tmux with `-u` doesn't seem to fix it.

**Comment by jwilm** [comment]
Issues with `tmux` rendering is often because of having the wrong `TERM` value set in/outside of `tmux`. Please verify that `TERM` is set to either `xterm-256color` (or an `alacritty-` variant if using our terminfo definitions) **outside** of `tmux`, and that the value **inside** `tmux` is set to one of the supported values which should be either `screen-256color` (or `tmux-256color` if using their terminfo definitions).

**Comment by jedahan** [comment]
@jwilm what would be the most minimal setup to achieve
`alacritty-256color` outside tmux, and `tmux-256color` inside tmux if on macOS?

**Comment by jwilm** [comment]
@jedahan first, install terminfo definitions for both TERM values. There's one for alacritty in the project root, but it will be getting replaced soon by a new PR. For `tmux`, you can search around the internet.

You can then update your alacritty.yml to set `TERM=alacritty-256color` in the `env:` section, and then in your tmux config, you can `set -g default-terminal "tmux-256color"`

**Comment by jedahan** [comment]
Thank you @jwilm this works perfectly.

**Comment by jwilm** [comment]
@jedahan were you experiencing this issue as well?

**Comment by jedahan** [comment]
No, I was just simplifying my TERM exports everywhere

**Comment by jedahan** [comment]
Well, I didn't try tmux integration. I will try it now.

**Comment by jedahan** [comment]
@freevova when you say integration, to you mean `tmux -CC` or just using tmux at all? For reference, my dotfiles are https://github.com/jedahan/dotfiles if any of that helps.

**Comment by xordspar0** [comment]
My `TERM` outside tmux was `xterm-256color` and inside tmux it was `screen`.

I did `set -g default-terminal "screen-256color"` in my `.tmux.conf`, but that didn't change the rendering issues.

**Comment by kulabun** [comment]
Same problem

**Comment by iicurtis** [comment]
Same here. Colors are broken with the default tmux config with `$TERM=screen-256color`, but they work fine with `set -g default-terminal "tmux-256color"`.

**Comment by khmelevskii** [comment]
when I start tmux as shell I have problems with my powerline, all font icons doesn't work. But when I run tmux manually everything works fine

**Comment by Double1996** [comment]
> @xordspar0 I fixed my issues by setting the right locale. Could you show your locale? Also, try to start tmux with the `-u` flag, and see if that fixes it. It forces tmux to use UTF-8.

Work！Thanks

**Comment by xordspar0** [comment]
I just tried the latest master commit and it works for me now. 🎉

**Comment by chrisduerr** [comment]
That's great to hear, thanks for the update!

Closing this issue as resolved then!
