### ISSUE TITLE
Some font characters look cut-off (incomplete rendering)

### ISSUE THREAD

**Issue by talal** [jwilm/alacritty#1860]
OS: macOS 10.14.1
Alacritty: 0.2.3 ([config-file](https://github.com/talal/dotfiles/blob/master/alacritty/alacritty.yml))
tmux: 2.8 ([config-file](https://github.com/talal/dotfiles/blob/master/tmux/))
font: Pragmata Pro Mono

Some font characters are not fully rendered, they are cut at the top. It is not that big of an issue but with some characters the difference is noticeable. I have particularly noticed it with `u` and `v`.

tmux is not the issue and neither is neovim since this issue also occurs outside neovim/tmux. e.g. `cat some-file`. The same font looks okay in iTerm.

Please refer to the screenshot below and look at the `u`, `v`, `x`, and `y` characters, their top part is incomplete and looks cut-off on the Alacritty side:
![font-cut](https://user-images.githubusercontent.com/3526562/49393976-07bcb300-f733-11e8-8b9c-291010dc160a.png)

Other fonts don't have this problem, I tried Monaco and it looked okay.

Also: 
- `use_thin_strokes` doesn't work, but I already saw another issue regarding that.
- `start_maximized` also doesn't work, it always starts with the `window.dimensions`. This feature is not that important to me.

Your help on this issue would be appreciated. To be honest, these issues don't bother me much, the speed difference in comparison with iTerm is worth it 😄

**Comment by dm1try** [comment]
@talal I was unable to reproduce the issue like on your screenshot above (`osx 10.14.1/alacritty master/Pragmata Pro Mono Regular/size`)
<img width="251" alt="screen shot 2018-12-04 at 02 38 42" src="https://user-images.githubusercontent.com/486807/49408540-bed62000-f76d-11e8-8945-df1e1132f33a.png">
 (disabling all font settings except antialising)
<img width="251" alt="screen shot 2018-12-04 at 02 29 40" src="https://user-images.githubusercontent.com/486807/49408286-b6c9b080-f76c-11e8-8c98-41d156573e7d.png">

> start_maximized also doesn't work, it always starts with the window.dimensions. This feature is not that important to me.

this one is fixed on master 0d47cd25b90deecc2dbf40c8361d2310049fdde7

>  the speed difference in comparison with iTerm

did you try to enable metal renderer in iTerm?

**Comment by chrisduerr** [comment]
This seems quite odd to me because there couldn't be an issue with a bounding box since these characters are shorter than all the other ones, ignoring the fact that Alacritty doesn't trim things that leave the bounding box of a glyph anyways.

So my assumption would be that the font stack returns the glyph the way it is displayed to you. We're using the core stuff on macOS which is their standard font rendering I believe, so the only guess I have as a non-macOS user would be that there's a font styling thing going on like thin strokes or similar. Or maybe iTerm and Alacritty are using different fonts that just look similar with most characters?

**Comment by chrisduerr** [comment]
@talal Does changing the font size alter the font? Maybe it's just rendered differently with certain font sizes?

Also is there anything special about this display? Like a vertical orientation or unusual RGB pixel layouts?

**Comment by talal** [comment]
> @talal Does changing the font size alter the font? Maybe it's just rendered differently with certain font sizes?

Yep, have a look at the screenshots below

`font.size: 17.0`:
![17](https://user-images.githubusercontent.com/3526562/49458518-42832180-f7ed-11e8-896e-597cf5776b4f.png)

`font.size: 18.0`:
![18](https://user-images.githubusercontent.com/3526562/49458424-0ea7fc00-f7ed-11e8-8c93-492cd4751179.png)

`font.size: 19.0`:
![19](https://user-images.githubusercontent.com/3526562/49458453-1b2c5480-f7ed-11e8-82c2-9cd3102f4907.png)

18 is the culprit, it is difficult to tell because of being zoomed in, but you can tell the by looking at the top of `x`

I'd also like to mention that `font.use_thin_strokes` didn't work for me before on my external display but doing the following made it work:

```
$ defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

`font.size: 19.0`, same as before but with the fix mentioned above:
![screenshot 2018-12-04 at 18 06 20](https://user-images.githubusercontent.com/3526562/49459685-e8d02680-f7ef-11e8-9852-3d706afbd6d0.png)

It might be worth mentioning this in `alacritty_macos.yml` in the thin stroke comment. This is due to the new font smoothing stuff in macOS Mojave (10.14.x), only non-retina displays are affected by this.

> Also is there anything special about this display? Like a vertical orientation or unusual RGB pixel layouts?
The display is in the normal orientation and no unusual RGB pixel layouts as far as I know.

By applying the thin stroke fix and changing the font size to 19, the quality looks pretty good even on my external display so feel free to close this ticket at your convenience and thanks for the help 😄

**Comment by chrisduerr** [comment]
Keeping this open as a tracking issue for the discussed documentation changes.

Help is always appreciated ofc, since I can't test macOS changes.

**Comment by NickeZ** [comment]
Did you try half sizes? like 18.5?

**Comment by talal** [comment]
> Did you try half sizes? like 18.5?

yeah, that also cuts-off

**Comment by talal** [comment]
@chrisduerr I think this can be closed, now that the documentation changes have been added.

**Comment by josepheiba** [comment]
I'm sorry, that was a pretty half arsed screenshot, hopefully you can see it now, I'm just reporting this issue. I tested another terminal emulator "kitty" and the font rendered correctly in macOS. Have a good day.

<img width="1077" alt="Screenshot 2023-03-20 at 4 33 36 PM" src="https://user-images.githubusercontent.com/101673502/226407403-83bdadc1-1210-4437-8344-bf963463e8fa.png">

**Comment by stepanbujnak** [comment]
I don't think this issue is solved by enabling AppleFontSmoothing and thin strokes. I'm getting my characters cut off just like the screenshot above. This is more prevalent on different font sizes, for example, setting a font size to `13.0` cuts the characters off from the top, setting it to `13.3` makes to top look good but it's cut from the side. I believe this to be an Alacritty issue also because it's only happening in Alacritty. I tried Terminal.app, iTerm, kitty, wezterm and they all render fine.

**Comment by dfl0** [comment]
> I don't think this issue is solved by enabling AppleFontSmoothing and thin strokes. I'm getting my characters cut off just like the screenshot above. This is more prevalent on different font sizes, for example, setting a font size to `13.0` cuts the characters off from the top, setting it to `13.3` makes to top look good but it's cut from the side. I believe this to be an Alacritty issue also because it's only happening in Alacritty. I tried Terminal.app, iTerm, kitty, wezterm and they all render fine.

I’m still having this exact issue as well, and it happens with every font in Alacritty, and none in any other terminal emulator I’ve used.
