### ISSUE TITLE
Config file not recognized

### ISSUE THREAD

**Issue by SirAiedail** [jwilm/alacritty#193]
I just installed Alacritty and copied the configuration file to `~/.alacritty.yml` as described in the README.
However no matter which value I change in that file, it won't be reflected in the terminal, even after restarting it.

Might be the reason for #192. Arrow keys on the other hand do work.

I'm running Fedora 25.

**Comment by rhaps0dy** [comment]
So maybe #172 is not exclusive to OS X!

**Comment by JacksonGariety** [comment]
I'm running Arch Linux and correct path seems to be `$HOME/.config/alacritty.yml`.

**Comment by 0X1A** [comment]
This issue seems to be difficult to pinpoint reading the other issues, I'm also on Fedora 25 and alacritty reads from `~/.alacritty.yml`. The environment variable `XDG_CONFIG_HOME` is not set on my machine.

**Comment by tmalsburg** [comment]
I'm experiencing the same issue as OP on Ubuntu 16.10.  I followed the instructions on the GitHub main page of the repo.

**Comment by rrichardson** [comment]
I'm on fedora 25 and with a little experimenting have found that the config priority is 

1.  ~/.config/alacritty.yml
2. ~/.alacritty.yml 

E.g. if you have a file in both places, it will use the ~/.config/alacritty.yml

**Comment by SirAiedail** [comment]
Oh, I see. I have the file `~/.config/alacritty.yml` even though I never created it.
I hadn't copied the default config when I first started Alacritty so I guess it auto created the one in `~/.config/alacritty.yml`.
Then all my changes to `~/.alacritty.yml` were ignored because the other file has higher priority.

**Comment by anderspitman** [comment]
Also on Arch. `~/.config/alacritty.yml` is working for me as well, and it was automatically created by Alacritty.

**Comment by 0X1A** [comment]
I think this issue should be closed. The configuration file from `~/.config` will be read/created if no file is found for `$HOME/.alacritty.yml`

**Comment by tmalsburg** [comment]
Thanks @rrichardson.  This may not be a software bug but it is a documentation bug that should be fixed.

**Comment by SirAiedail** [comment]
I think it is still an issue with the documentation. Right now the Readme says that you must copy the configuration or otherwise stuff like the arrow keys will not work. So if someone skips copying the config file like I did and does it after the first launch, he won't notice the file in `~/.config` and keep wondering why edits to `$HOME/.alacritty.yml` won't work.

**Comment by anderspitman** [comment]
I think #191 will get it.

**Comment by SirAiedail** [comment]
You're right @anderspitman.

**Comment by anderspitman** [comment]
Well I think in it's current incarnation #191 doesn't mention that the config is automatically created for you, but I added a reference to this issue asking for that to be added. I don't think it would hurt to keep this open until it's merged.

**Comment by Pk13055** [comment]
While this doe not really solve the issue, a quick fix was just soft-linking my config `~/.alacritty.yml` to every other place.
```bash
ln -sf ~/.alacritty.yml ~/.config/alacritty/alacritty.yml
ln -sf ~/.alacritty.yml ~/.config/alacritty.yml
```

**Comment by chrisduerr** [comment]
I'm actually a big fan of not creating any config files at all. There's no technical requirement for us to have a config file present because the default config file is compiled into alacritty. I usually like my applications to cleanly uninstall unless I have created a config myself, but there are arguments against this too.

**Comment by zerols** [comment]
i intsall in win10 , when i open it , it show me this 
 
Created log file at "C:\Users\zero\AppData\Local\Temp\Alacritty-17268.log"
[2020-04-18 17:30:46.807377200] [INFO] Welcome to Alacritty
[2020-04-18 17:30:46.808375500] [INFO] No configuration file found
[2020-04-18 17:30:46.811405800] [DEBUG] Estimated DPR: 1.1458333333333333
[2020-04-18 17:30:46.811405800] [DEBUG] Estimated Cell Size: 9 x 19
[2020-04-18 17:30:46.811405800] [DEBUG] Estimated Dimensions: None
[2020-04-18 17:30:46.873374300] [INFO] Device pixel ratio: 1.1458333333333333 C:\Users\zero\Desktop
>>> [2020-04-18 17:30:46.897950700] [INFO] Initializing glyph cache...
[2020-04-18 17:30:46.921976100] [INFO] ... finished initializing glyph cache in 0.0245663s
[2020-04-18 17:30:46.922951800] [INFO] Cell Size: 9 x 19
[2020-04-18 17:30:46.923952900] [INFO] Padding: 0 x 0
[2020-04-18 17:30:46.923952900] [INFO] Width: 1024, Height: 768
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
thread panicked while processing panic. aborting.
how shold i creat config log

**Comment by chrisduerr** [comment]
See #3590.
