### ISSUE TITLE
Setting colours 17+ in shell on Windows using conpty

### ISSUE THREAD

**Issue by Woodham** [jwilm/alacritty#2074]
I've been reading through issues trying to figure out whether this is supposed to work or not, but I'm honestly not sure.

Using the Conpty setting on windows definitely enables showing of 256 colours, but using e.g. https://github.com/chriskempson/base16-shell to set colours 16..21 doesn't seem to work. The output of the provided colortest script in base16-shell shows they are not being set, whereas they work fine in e.g. wsltty.

Alacritty:
![image](https://user-images.githubusercontent.com/83042/52243505-c9c64180-28d1-11e9-8d38-4c23bc8e524d.png)

Wsltty:
![image](https://user-images.githubusercontent.com/83042/52243526-d8acf400-28d1-11e9-8cf5-bada4cb04d8c.png)

**Comment by chrisduerr** [comment]
Have you tried setting the indexed_colors in the Alacritty configuration? I'm not familiar with what the base16 script does.

**Comment by Woodham** [comment]
My understanding is it uses escape sequences to change the terminal's colours at runtime. For example:

`echo -en "\033]4;17;rgb:ff/00/00\007"` - this should set colour 17 to red
`echo -en "\\033[38;5;17m RED\t\\033[0m\n"` - this should display the word "RED" in colour number 17.

However in Alacritty:

![image](https://user-images.githubusercontent.com/83042/52245689-9d62f300-28da-11e9-9de6-ee2541d604f0.png)

The same commands in Wsltty:

![image](https://user-images.githubusercontent.com/83042/52245725-b9669480-28da-11e9-8c03-d36e9c2c3883.png)

Also I should note that setting these colours also works fine in the OSX version of Alacritty.

**Comment by Woodham** [comment]
I also just realised I totally left out I'm using `wsl.exe` as my shell.

**Comment by Woodham** [comment]
Sure:

![image](https://user-images.githubusercontent.com/83042/52246225-ec118c80-28dc-11e9-8b82-a6eb96e0a4d1.png)

The same issue occurs when using `wsl.exe` or `bash.exe`. I've tried and had some issues previously using `wslbridge.exe` working propoerly in alacritty. When I use the one used by Wsltty I get this:

![image](https://user-images.githubusercontent.com/83042/52246359-72c66980-28dd-11e9-8177-dcf5ec76ebdd.png)

No colours seem to work and it prints a bunch of backslashes at the beginning (maybe something in my bashrc? Don't know)

**Comment by Woodham** [comment]
Also to be clear the escape sequence for setting the colours works for colours 1-16, just not anything in the 256 colour space.

**Comment by chrisduerr** [comment]
Could you test setting these colors in the `indexed_colors` in the config? Just to make sure that Alacritty isn't setting them properly, but they get overwritten or something.

If the indexed colors work, we should be able to rule that out.

**Comment by Woodham** [comment]
No problem - I've tried setting colour number 17 to red using `alacritty.yml` like this:

![image](https://user-images.githubusercontent.com/83042/52297800-714a7f00-2979-11e9-99b9-843705a5feda.png)

And tried echoing it out again:

![image](https://user-images.githubusercontent.com/83042/52297862-93dc9800-2979-11e9-985d-3112f203f661.png)

So it doesn't seem to set those colours at all. I also tried doing some other tests - I completely disabled my bashrc to make sure it was nothing I was doing - same issue, and I also tried disabling conpty, still the same issue. 

It seems like neither the escape codes nor the `indexed_colors` property can change colours over the first 16 on Windows when using WSL?

**Comment by chrisduerr** [comment]
Is the config file printed by `alacritty -v` actually what is being used? And have you tried using the WinPTY/without WSL?

**Comment by Woodham** [comment]
I'm sure the config file is the one being used as it's the same one I was using the enable/disable Conpty.

I haven't tried using it without WSL, I'll try and find a way of testing `indexed_colors` using it when I get home. Does the normal windows console support colours higher than 16 bit?

**Comment by chrisduerr** [comment]
I believe the WinPTY does not support colors higher than 16bit, but I thought the ConPTY API did.

**Comment by chrisduerr** [comment]
Also note that https://github.com/jwilm/alacritty/issues/1792 and https://github.com/jwilm/alacritty/issues/1662 are related to this. Though I believe both of these should be fixed with the ConPTY.

**Comment by davidhewitt** [comment]
I think JDTX has identified the problem in his recent comment in #1792. That changelog suggests this is a bug in microsoft's side of the conpty code that's already fixed in insider builds. Most users would therefore see this fix in the Windows 10 19H1 release.

(I'm not currently running an insider build, but I could switch over to one and verify this is fixed if you like.)

**Comment by chrisduerr** [comment]
Closing this since it sholud be fixed then. Also since it kinda is a duplicate of #1792.

If anyone can't get this to work with the latest conpty release, please let me know and I can re-open.

**Comment by Woodham** [comment]
Yep I agree, looking at that Windows blog I belive this is what should fix this issue https://github.com/Microsoft/console/issues/313

**Comment by saifali96** [comment]
@chrisduerr I can confirm that the issue still exists, I'm using Windows 10 19H1, build number 18362 [released today] and I have run the same colortest, it fails and produces the same output as the OP.

I have enabled the experimental ConPty support in the config.yml file and also tested it if it's indeed under ConPty.

Can you please reopen the issue?

**Comment by chrisduerr** [comment]
@saifali96 Which shell did you test this in? Should probably try with bash to make sure. I don't know if cmd does that stuff at all.

**Comment by saifali96** [comment]
@chrisduerr I ran it in fish, but I also just ran it in bash, still doesn't work.

**Comment by chrisduerr** [comment]
Would you mind posting the config you've used to test this?

**Comment by saifali96** [comment]
Do you mean the `alacritty.yml` file

**Comment by chrisduerr** [comment]
I do. I'd assume you've added colors there if you want to test if setting colors past 16 works?

**Comment by chrisduerr** [comment]
Yeah, that color script will not show anything special unless you've got those colors actually set. So I'd assume it's working as intended.

**Comment by saifali96** [comment]
No, sorry I haven't. How does one go about adding colors?

**Comment by chrisduerr** [comment]
Take a look at the `indexed_colors` field in the configuration file. There should hopefully be all the required documentation right there, if it is not, please open an issue.

**Comment by saifali96** [comment]
@chrisduerr , thank you very much for your help, unfortunately I'm unable the set colors, here's what is in my config file:

```yml
indexed_colors:
    - { index: 16, color: '0xff00ff' }
    - { index: 17, color: '0xdc9656' }
    - { index: 18, color: '0xDC9656' }
    - { index: 19, color: '0xff00ff' }
    - { index: 20, color: '0xb77ee0' }
    - { index: 21, color: '0xe8e8e8' }
```

And here's the output still, I have tried to add the colors from the script as well as well an example/default color:

![image](https://user-images.githubusercontent.com/6160857/58268285-75ae7280-7d85-11e9-999f-2d5e3bd861cd.png)

**Comment by chrisduerr** [comment]
I'll take a look to verify, thanks.

**Comment by davidhewitt** [comment]
Are you guys still having problems with this? I just ran the test above and it worked fine for me. I'm on Windows 10 Insider build 18362.10022 (current Slow Ring release).

![image](https://user-images.githubusercontent.com/1939362/66190660-7258bb00-e684-11e9-9213-22d44791d796.png)

(Perhaps the fix didn't make 19H1 in the end, might land in 19H2?)

**Comment by chrisduerr** [comment]
I reopened to take a look myself @davidhewitt, though it looks like everything's good. Thanks for testing.

**Comment by Woodham** [comment]
Just for completeness this is working fine for me too. 

![image](https://user-images.githubusercontent.com/83042/66225169-4e6a9900-e6c7-11e9-9b44-ba215b92bf4c.png)

I'm not on an insider build - Windows version 1903 build 18362.388
