### ISSUE TITLE
Opacity setting not applied

### ISSUE THREAD

**Issue by tkinz27** [jwilm/alacritty#2254]
Which operating system does the issue occur on?
Linux -- Ubuntu 19.04 dev
If on linux, are you using X11 or Wayland? X11

This issue might be more question on how to debug this rather than there is an actual issue. Recently I updated alacritty to the latest master (dbce674d7012fe09b3ab9ac0aeeb1c748bb7afce) and install using `cargo deb --install`. My opacity setting is no longer being applied. I have also recently gotten an external gpu and have been messing with the gpu drivers (switching between nvidia versions and nouveau) so I'm not necessarily convinced this is an issue with the latest Alacritty. When running under sway window manager the opacity works, but under gnome (3.32) on X11 the opacity setting does not. 

I have tried running alacritty with the `-vvv` option but haven't seen any errors or logs that seem relevant. I'm still learning about how all the pieces work together recently switching over from mac to linux so I'm not sure where to look next for why the opacity is not working.

**Comment by chrisduerr** [comment]
I'm not aware of an isuse with opacity on Linux. The only two things that are commonly issues with this is that people think it's a transparency (not opacity, which is the opposite) setting and that no compositor is running.

I'd expect GNOME on X11 to be running a compositor by default, however making sure that compositing is working properly is probably your best bet.

There's likely no logging in Alacritty's output because Alacritty doesn't run into any issues. If Alacritty attempts to render a transparent window and there is no issue, but the window manager doesn't render it with transparency, there's little Alacritty can do since it doesn't know anything about that.

**Comment by stkw0** [comment]
After updating alacritty I had similar issues, now transparency doesn't work. I am using xcompmgr as the compositor, and all the settings are the same than before updating alacritty.

**Comment by chrisduerr** [comment]
I've verified myself with `compton` and i3 and I can not reproduce this issue. Transparency works as expected.

I'm curious if a fully transparent window with `background_opacity: 0` will have a black background or if it will have the background set in the `colors` section?

**Comment by stkw0** [comment]
I tried with compton just in case, and still transparency doesn't work on alacritty. When opacity is set to 0 it seems that alacritty only displays a black background

**Comment by stkw0** [comment]
Update, I don't have this problem with version 0.2.9

**Comment by stkw0** [comment]
Update2: Seems that the commit which introduced the problem was "0f96a62"

**Comment by FliiFe** [comment]
I am also experiencing this issue, after upgrading to 0.3.0.
The `background_opacity` setting does change the background, but just the shade (`0.0` is plain black, `1.0` is the set color)

**Comment by chrisduerr** [comment]
> i3 with compton, on 0.3.0-rc1 (latest ebuild)

Now that is interesting, it's pretty much the same system I've just tested it on and things worked great.

Could you share some more system information (especially GPU+drivers and kernel version)?

**Comment by chrisduerr** [comment]
Also would be interesting to have this re-tested with latest master since this bumps the Glutin version.

**Comment by FliiFe** [comment]
```
$ uname -a
Linux fliife-computer 5.0.7-gentoo #1 SMP Sat Apr 6 22:12:52 CEST 2019 x86_64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz GenuineIntel GNU/Linux
```

I use the kernel driver for intel graphics (integrated gpu)

I'll try with master and see if things change

**Comment by FliiFe** [comment]
Master does seem to fix the issue, though I'm not entirely sure (when I run `target/debug/alacritty --version`, it returns `alacritty 0.2.9`).
I've seen the ebuild for 0.3.0 which uses sed to replace version number, so I'm guessing someone just forgot to bumb the version number somewhere ? Or am I going the wrong way about this ?

**Comment by chrisduerr** [comment]
The version number usually stays the same until the next release is made, so that's intentional.

I would have expected you to run maybe Nvidia since that's the most likely to show difficulties, but I guess you're running mesa too then.

Note that I'm running amdgpu with mesa on Archlinux and everything's working for me.

I'd be interested in getting some more hardware information from everyone who can reproduce this issue, including kernel version, gpu driver, glxinfo output and compositor/WM. Maybe that can give us some hints.

Since this was apparently caused by an upstream change, I've also reported the issue upstream here:
https://github.com/tomaka/winit/issues/832

If anyone here is willing to bisect winit to check where this issue might be coming from, that would be very helpful. It might be a bit laborious but would hopefully give us a pretty good idea of what caused this. If someone is interested and needs help, please let me know. If someone found the bad commit, please report it to the upstream issue.

**Comment by FliiFe** [comment]
[Here](http://dpaste.com/1AQT5BA.txt) is my glxinfo output

**Comment by stkw0** [comment]
Same for me, with master it seems to work fine. I'm using Gentoo, Linux 5.0.5, nvidia, xcompmgr and dwm. Here is my glxinfo http://dpaste.com/1EVK7XQ

**Comment by chrisduerr** [comment]
Oh I totally misunderstood @FliiFe and thought he said master does **not** fix the issue, oops.

Looks like the issue is resolved then.

**Comment by farseerfc** [comment]
Still cannot apply opacity since alacritty 0.3.0
OS: Arch Linux 
WM: kwin5
GPU driver: xf86-video-radeon

Tried both glutin 0.21.0-rc1 and 0.21.0-rc2 (changing `PossiblyCurrentContext` to `PossiblyCurrent`)

**Comment by farseerfc** [comment]
My glxinfo is pasted here: https://fars.ee/5J07

**Comment by chrisduerr** [comment]
I've reopened the upstream issue: https://github.com/tomaka/winit/issues/832

**Comment by farseerfc** [comment]
The same problem is also reproduced on my another PC with Intel integrated GPU.
OS: Arch Linux
WM & Compositor: kwin5
Mesa: 19.0.1-2
GPU driver: modesetting DDX with i965 kernel driver
glxinfo: https://fars.ee/YoO6

On this Intel machine, I did a git bisect on the commit history of alacritty. the last good commit (that can show transparency) is cd8d537bed98559ed49c1465db84ecec5393119f and the first bad commit (that shows total opacity) is 6757acbb824e8be9968529a66e9a75a0a2ea2f5d .

**Comment by farseerfc** [comment]
Reverting glutin to "bsd-build-fix" branch can also fix the issue on my intel PC.
Here is a full diff for reverting glutin: https://fars.ee/ktHw/diff

**Comment by ngortheone** [comment]
I am also affected after upgrade to 0.3. Reducing `background_opacity` only makes background darker, but wallpaper behind it is not visible

OS: ArchLinux
WM: i3 + compton
```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile)
	Subsystem: Lenovo UHD Graphics 630 (Mobile)
	Kernel driver in use: i915
```

**Comment by stfnm** [comment]
I'm also having that problem with the current alacritty master (aac62ce5acd2ef4d05a54bc13b7cf30c30f129b2).

Infos about my system:
* Fully up-to-date Arch Linux x86_64
* Linux Kernel: 5.0.7
* CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
* GPU: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
* i3 version 4.16.1 (2019-01-27
* xcompmgr v1.1.8
* Xorg 1.20.4
* glxinfo: https://gist.github.com/stfnm/f1d43f31f79731d6688c24cee9aeef59

**Comment by moderation** [comment]
I'm running master (`alacritty --version` is `0.3.0`) and also have lost opacity. Xubuntu 18.04, `4.15.0-47-generic`, `rustc --version` is `rustc 1.34.0 (91856ed52 2019-04-10)`

**Comment by Ghoughpteighbteau** [comment]
farseerfc is pretty much right. I basically reverted the glutin version change at 6757acbb824e8be9968529a66e9a75a0a2ea2f5d and 56fea343ff94b23aa94f8756643c015f20517e8f. Opacity works after that. :\

diff here:

```
diff --git a/Cargo.toml b/Cargo.toml
index d1ad1bc..f410e74 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -42,7 +42,7 @@ clap = "2"
 fnv = "1"
 unicode-width = "0.1"
 arraydeque = "0.4"
-glutin = { version = "0.21.0-rc2", features = ["icon_loading"] }
+glutin = { git = "https://github.com/chrisduerr/glutin", branch = "bsd-build-fix", features = ["icon_loading"] }
 env_logger = "0.6.0"
 base64 = "0.10.0"
 static_assertions = "0.3.0"
diff --git a/src/window.rs b/src/window.rs
index b471bbd..14316bb 100644
--- a/src/window.rs
+++ b/src/window.rs
@@ -21,8 +21,8 @@ use glutin::os::unix::EventsLoopExt;
 #[cfg(windows)]
 use glutin::Icon;
 use glutin::{
-    self, ContextBuilder, ControlFlow, Event, EventsLoop, MouseCursor, PossiblyCurrent,
-    WindowBuilder,
+    self, ContextBuilder, ContextTrait, ControlFlow, Event, EventsLoop, MouseCursor,
+    PossiblyCurrentContext, PossiblyCurrentContextTrait, WindowBuilder,
 };
 #[cfg(windows)]
 use image::ImageFormat;
@@ -54,7 +54,7 @@ type Result<T> = ::std::result::Result<T, Error>;
 /// Wraps the underlying windowing library to provide a stable API in Alacritty
 pub struct Window {
     event_loop: EventsLoop,
-    windowed_context: glutin::WindowedContext<PossiblyCurrent>,
+    windowed_context: glutin::WindowedContext<PossiblyCurrentContext>,
     mouse_visible: bool,

     /// Whether or not the window is the focused window.
@@ -120,7 +120,7 @@ fn create_gl_window(
     event_loop: &EventsLoop,
     srgb: bool,
     dimensions: Option<LogicalSize>,
-) -> Result<glutin::WindowedContext<PossiblyCurrent>> {
+) -> Result<glutin::WindowedContext<PossiblyCurrentContext>> {
     if let Some(dimensions) = dimensions {
         window = window.with_dimensions(dimensions);
     }
```
I'm otherwise unsure of the implications of this change. Will void warranty.

**Comment by dermetfan** [comment]
Lost opacity with `0.3.0` running Nvidia dedicated card through Intel integrated graphics.

[glxinfo](https://0x0.st/zNCA.txt)

<details>
<summary>Relevant NixOS config</summary>

```
services.xserver.videoDrivers = [ "nvidia" ];

hardware.nvidia = {
  modesetting.enable = true;

  optimus_prime = {
    enable = true;
    nvidiaBusId = "PCI:1:0:0";
    intelBusId  = "PCI:0:2:0";
  };
};
```

</details>

**Comment by dmp450** [comment]
I'm having the same problem. Running `0.3.2` + Compton + awesome on Gentoo. I first noticed the problem on `0.3.0`.

**Comment by Sogomn** [comment]
Same problem on Void Linux, seems to be independent of the OS.

Void Linux, Compton, i3, nVidia proprietary drivers, [glxinfo](https://pastebin.com/04bqdd25)

**Comment by farseerfc** [comment]
After discussing with my friend who use a nvidia driver and compton+i3, I think my previous description need some clarification.

There might be 2 separate phenomenon here with regards to transparency / opacity of the background color:
1. Starting before 0.3.x, around 0.2.x, alacritty on nvidia + compton has a total transparent background. i.e. alacritty always behave as if background_opacity is set to "0.0". The texts are still in full opacity, therefore not readable. This behavior is NOT reproducible on kwin5_x11, where kwin5_x11 correctly shows a semi-transparent background color according to background_opacity option value.
2. Starting from 0.3.0 (with glutin switching to upstream branch), alacritty lost the ability of showing semi-transparent background. i.e. alacritty always behave as if background_opacity is set to "1.0". This behavior is occurring regardless of the compositor (kwin or compton) and the GPU driver (intel or nvidia) in use.

Switching glutin back to "bsd-build-fix" on 0.3.0 and above will solve the second issue, with the first issue remaining.

Also here is an updated patch to revert glutin on 0.3.2: https://fars.ee/uHas/diff

**Comment by chrisduerr** [comment]
After the continued discussion here I've decided to retest this on my system and it looks like it's broken for me too. I originally thought this would just affect a few systems with specific configuration, but it looks like after the upstream 'fix' things got much worse and now all X11 systems are affected. It looks like I must have mixed up some branches when testing.

I've updated the upstream issue to represent that, I'll try to get to the bottom of this.

**Comment by kronolynx** [comment]
I'm having the same problem in Xmonad + Compton on ubuntu 19.4

**Comment by juchiast** [comment]
I'm having this problem with xcompmgr + i3 on Fedora 29.

**Comment by raffael-sfm** [comment]
I'm getting crashes on alacritty start-up when transparency patch is applied.
Here is the patch mentioned: https://git.archlinux.org/svntogit/community.git/plain/trunk/fix-transparency-0.3.2.patch?h=packages/alacritty
Please not the glutin downgrade.
My system is Arch Linux x86_64, Xfce, older 340.xxx Nvidia drivers.
I'm attaching glxinfo output and the backtrace.
The package works for me without transparency patch applied. Since I don't really care about this thing, I'm happy. However, if I can assist you with debugging/testing it, please let me know.
[glxinfo.txt](https://github.com/jwilm/alacritty/files/3174292/glxinfo.txt)
[alacritty.log](https://github.com/jwilm/alacritty/files/3174295/alacritty.log)

**Comment by pmalek** [comment]
Also getting this issue on
* Ubuntu 14.04.06
* kernel (doesn't really matter) but currently 5.0.17
* X.Org version: 1.15.1

`0.2.9` works fine.

**Comment by zapateo** [comment]
Same problem with bspwm + compton on Fedora 30 (Xorg version 1.20.4)

**Comment by pmalek** [comment]
Still the same with:
- Ubuntu 18.04
- X.Org version: 1.20.1
- nvidia drivers 430.26

[`707f429`](https://github.com/jwilm/alacritty/commit/707f4293667d4d8564ab0afc13128463c2ee7fd5)

**Comment by geocool** [comment]
#2438 pull request mentioned above, solves opacity for me.

**Comment by pmalek** [comment]
@geocool I can confirm it works for me as well :)

**Comment by chrisduerr** [comment]
This has been resolved in the EventLoop 2 branch for a long time and is planned to land in 0.3.4 (the next release). Locking this thread to keep the +1 'spam' to a minimum.
