### ISSUE TITLE
zsh tab completion does not print

### ISSUE THREAD

**Issue by d3rrial** [jwilm/alacritty#230]
This is how it looks for me:
![tabc](https://cloud.githubusercontent.com/assets/3718129/21749673/b77ecd9a-d5a3-11e6-8119-61dd136ee2ff.gif)
How it should look is that everything is already visible and just the white highlighting moves, not new things being printed
I'm using the diff from #85 that fixes the htop bars.

**Comment by okuuva** [comment]
I have a similar problem, but only the last line of auto complete candidates is invisible. Could you try that with some command that has a lot of candidates, like `cd a <tab>` in `/usr/share` in order to see if you have a similar behavior?

**Comment by d3rrial** [comment]
Just tried and I do indeed have the same problem as well. The first ones are printed in that case, but the last line is not.

**Comment by theduke** [comment]
@d3rrial this is fixed for my with the latest master.

**Comment by stkw0** [comment]
I used the last master and I have the same problem.

**Comment by d3rrial** [comment]
@theduke I'm on the latest commit in the master branch, it's not fixed yet.
If it works for you but doesn't work for me, what shell do you use? How does it look when you tab through?

**Comment by theduke** [comment]
zsh also.

Ah, on closer inspection: only one line of completions is visible when I first press tab.
On continues presses additional lines show up and get highlighted.

**Comment by d3rrial** [comment]
@theduke The entire last line isn't drawn. Since my command suggestion only had one line, nothing was drawn. If it has more lines, the first ones are shown while the last ones are invisible. At least that's how it looks to me.

**Comment by gutigen** [comment]
I can confirm this happening on Arch Linux with Intel Haswell, however if I try same thing inside tmux session, it works just fine.

**Comment by d3rrial** [comment]
@gutigen When I use GNU Screen, I have the same problem as described in the original post, and when I use tmux, the problem doesn't occur, just as you have described it. I assume that it's maybe because tmux is using ncurses or something like that to draw the terminal contents, while the others just draw regularly (no idea if that's actually what's happening!)

**Comment by theduke** [comment]
@jwilm this is still not working, and it's quite a critical bug for me, and probably for others too. ( In the sense that I prefer a terminal that works...)

Any idea what's the issue here?

ps: when running tmux on top, completions work.

**Comment by jwilm** [comment]
> it's quite a critical bug for me, and probably for others too.

Myself included ;)

I'm expecting this to be a pretty trivial fix, just need to make time to dig into it.
