### ISSUE TITLE
Artifacts with UTF-8 long characters

### ISSUE THREAD

**Issue by dmilith** [jwilm/alacritty#2463]
Which operating system does the issue occur on?

macOS 10.11.6, but also 10.14.x

Screenshot from Weechat + Wee_slack.py running under latest Alacritty:

Example screenshot: http://s.verknowsys.com/62efebe97a0636e4b1de9825314d4b8e.png

**Comment by chrisduerr** [comment]
Which Alacritty version are you running (you can see with `alacritty --version`)?

**Comment by dmilith** [comment]
Latest v0.3.2 :)

**Comment by dmilith** [comment]
I have reproduction path, it's quite easy. http://s.verknowsys.com/6f029f4cb27834eba97f2a99a2e3fd29.png

I just used 3 UTF-8 chars, then deleted message.. and like last byte of long char is still there (visible as smiley at end).

What I use:

Weechat 2.4 + Wee_slack (latest) on just one of Slack groups.

My input:

"test 🌃 👋 😄"

then I just did 's///' (which means - remove last message). Result is shown above :)

**Comment by dmilith** [comment]
I just noticed it's not only that.. it's general issue wherever I used "long UTF-8 characters". Like here: http://s.verknowsys.com/8970c390916c3fed9f573e54a9e2f8f6.png

(appears after just typing more messages in Weechat window)

**Comment by chrisduerr** [comment]
Seems like you've got the tab width set in the config, should be fixed once you follow the instructions in the comments about tab width or change it back to `8`.

**Comment by dmilith** [comment]
Nope. With default tab width 8 issue is the same.

**Comment by dmilith** [comment]
Here's my current configuration: https://gist.github.com/1ba78540a30f88c026760cbad53e57a3

Rendering issue is where it was. This bug still persists.. You shouldn't close it without confirmation of the reporter.

**Comment by dmilith** [comment]
After installation of alacritty terminfo my config uses "alacritty" as TERM:

https://gist.github.com/7fc4b9a81ea1a360d1dd9118228d55c9

Issue is still the same.

**Comment by chrisduerr** [comment]
Sorry for closing it prematurely. It looks like this is due to mismatch of the system's and Alacritty's unicode width functions.

This is already tracked in https://github.com/jwilm/alacritty/issues/1295, so all further discussion should move there.

**Comment by dmilith** [comment]
After testing I see that this issue happens only on my 10.11.6 (macpro). On 10.14.4 (mbp) with terminfo set to alacritty that issue doesn't exist. Thanks!
