### ISSUE TITLE
3-byte crash 

### ISSUE THREAD

**Issue by dnsjts** [jwilm/alacritty#515]
alacritty crashes when I issue the following command:
```bash
echo 6KWe | base64 -d
```

Found by `cat`ting the `/dev/urandom` again. (Might be related to #499 .)

Backtrace:
```
thread 'main' panicked at 'index 25 out of range for slice of length 24', /checkout/src/libcore/slice/mod.rs:672

stack backtrace:
stack backtrace:
   0:     0x55f7c9786e23 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hab274209b3900f9c
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55f7c9783034 - std::sys_common::backtrace::_print::h8f655fc4b25b9b70
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x55f7c978cc37 - std::panicking::default_hook::{{closure}}::hd0f0fde26cdd4a91
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x55f7c978c7fc - std::panicking::default_hook::h123df66825ae8c79
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x55f7c978d10b - std::panicking::rust_panic_with_hook::h3635757261b59272
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x55f7c978cfe4 - std::panicking::begin_panic::he3b450c9ca51fd2b
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x55f7c978cf19 - std::panicking::begin_panic_fmt::hf44dbae7fe247adf
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x55f7c978cea7 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x55f7c97b7ded - core::panicking::panic_fmt::hde6a1a29c4abc8e6
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x55f7c97b7ee9 - core::slice::slice_index_len_fail::h8d6a353e66085a31
                               at /checkout/src/libcore/slice/mod.rs:672
  10:     0x55f7c9737e47 - <core::ops::Range<usize> as core::slice::SliceIndex<[T]>>::index::ha12f7058d2f2ddad
                               at /checkout/src/libcore/slice/mod.rs:803
  11:     0x55f7c972aace - core::slice::<impl core::ops::Index<I> for [T]>::index::h19b918c17299cb0b
                               at /checkout/src/libcore/slice/mod.rs:654
  12:     0x55f7c973b4d2 - font::ft::FreeTypeRasterizer::get_rendered_glyph::ha10889efce849e32
                               at /home/amozes/workspace/github/alacritty/font/src/ft/mod.rs:217
  13:     0x55f7c973b029 - font::ft::FreeTypeRasterizer::get_rendered_glyph::ha10889efce849e32
                               at /home/amozes/workspace/github/alacritty/font/src/ft/mod.rs:194
  14:     0x55f7c973992d - <font::ft::FreeTypeRasterizer as font::Rasterize>::get_glyph::h865be892ed938886
                               at /home/amozes/workspace/github/alacritty/font/src/ft/mod.rs:85
  15:     0x55f7c92e8ed6 - alacritty::renderer::GlyphCache::get::{{closure}}::h25eb2135d53f0bf2
                               at /home/amozes/workspace/github/alacritty/src/renderer/mod.rs:270
  16:     0x55f7c92a286a - <std::collections::hash::map::Entry<'a, K, V>>::or_insert_with::h64977a0049ce1560
                               at /checkout/src/libstd/collections/hash/map.rs:1936
  17:     0x55f7c92e8dd6 - alacritty::renderer::GlyphCache::get::h533abf2b25792cdc
                               at /home/amozes/workspace/github/alacritty/src/renderer/mod.rs:267
  18:     0x55f7c92ec19c - alacritty::renderer::RenderApi::render_cells::h709352b1c43cc71b
                               at /home/amozes/workspace/github/alacritty/src/renderer/mod.rs:785
  19:     0x55f7c92e4b1e - alacritty::display::Display::draw::{{closure}}::hf31aab8dbf3ee1a0
                               at /home/amozes/workspace/github/alacritty/src/display.rs:299
  20:     0x55f7c92ea775 - alacritty::renderer::QuadRenderer::with_api::h6adcf7ff439417bb
                               at /home/amozes/workspace/github/alacritty/src/renderer/mod.rs:610
  21:     0x55f7c92e4734 - alacritty::display::Display::draw::h86ecf4d9d58d2ac0
                               at /home/amozes/workspace/github/alacritty/src/display.rs:297
  22:     0x55f7c915bcdd - alacritty::run::h1531f576730b74a1
                               at /home/amozes/workspace/github/alacritty/src/main.rs:172
  23:     0x55f7c915a57c - alacritty::main::hb27efce3c2542868
                               at /home/amozes/workspace/github/alacritty/src/main.rs:64
  24:     0x55f7c979405a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  25:     0x55f7c978d8aa - std::rt::lang_start::ha5350a26f8f175ab
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  26:     0x55f7c915c322 - main
  27:     0x7fbd4fc78290 - __libc_start_main
  28:     0x55f7c90b47a9 - _start
  29:                0x0 - <unknown>
```

**Comment by m-wynn** [comment]
I think I'm getting a similar error
```
thread 'main' panicked at 'index 27 out of range for slice of length 26', src/libcore/slice.rs:578
stack backtrace:
   1:     0x55e3d755a73a - <unknown>
   2:     0x55e3d7559bc1 - <unknown>
   3:     0x55e3d7558d1c - <unknown>
   4:     0x55e3d7558861 - <unknown>
   5:     0x55e3d75587d9 - <unknown>
   6:     0x55e3d756e0e6 - <unknown>
   7:     0x55e3d756df03 - <unknown>
   8:     0x55e3d75395b4 - <unknown>
   9:     0x55e3d7539160 - <unknown>
  10:     0x55e3d7455280 - <unknown>
  11:     0x55e3d73b0176 - <unknown>
  12:     0x55e3d73a7be8 - <unknown>
  13:     0x55e3d73b6990 - <unknown>
  14:     0x7f2da78e84e0 - __libc_start_main
                        at ../csu/libc-start.c:295
  15:     0x55e3d7372be9 - <unknown>
  16:                0x0 - <unknown>
```

**Comment by zhaihj** [comment]
Works for me.
Maybe it have been fixed?

alacritty version: commit a99a69cfcb983b923cb89c6faf5ace3b89d786a5

```
INSERT$ echo 6KWe | base64 -d
襞%      
```

**Comment by JIghtuse** [comment]
Works for me too, on the same commit @zhaihj has.

**Comment by dnsjts** [comment]
It still crashes on my machine, maybe there is some environment related cause.

@JIghtuse This is how I did it:

```fish
#!/bin/fish
while true;
    echo (head -c 8 /dev/urandom | base64) >> /tmp/asd.txt;
    tail -1 /tmp/asd.txt | base64 -d;
    sleep 0.1;
end;

**Comment by jwilm** [comment]
@dnsjts would you mind sharing your Alacritty font configuration section?

**Comment by dnsjts** [comment]
Here you go.

```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: Source Code Pro # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: monospace # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: monospace # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic

  # Point size of the font
  size: 9.0
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 2.0
    y: -7.0
```

**Comment by jwilm** [comment]
Hmm, not able to repro with that config. Since it's a CJK symbol, I wonder if we are getting a different fallback font.

**Comment by jwilm** [comment]
@dnsjts which version of freetype are you running with?

**Comment by Somelauw** [comment]
I'm using FreeType 2.6.3.
This error occurs with the following settings:
```
    family: Anonymous Pro
    size: 10
```

On bigger font sizes (size = 11, 12), it runs fine.

##### Traceback
```
thread 'main' panicked at 'index 4 out of range for slice of length 3', /checkout/src/libcore/slice.rs:578
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice.rs:578
   7: font::ft::FreeTypeRasterizer::get_rendered_glyph
             at /checkout/src/libcore/slice.rs:709
             at /checkout/src/libcore/slice.rs:560
             at ./font/src/ft/mod.rs:214
   8: alacritty::renderer::GlyphCache::load_and_cache_glyph
             at ./font/src/ft/mod.rs:82
   9: alacritty::display::Display::new
             at ./src/renderer/mod.rs:245
             at ./src/display.rs:160
             at ./src/renderer/mod.rs:651
             at ./src/display.rs:159
  10: alacritty::run
             at ./src/main.rs:85
  11: alacritty::main
             at ./src/main.rs:64
  12: main
  13: __libc_start_main
  14: _start

[2]  + 3943 exit 101   RUST_BACKTRACE=1 ./target/release/alacritty
```

**Comment by jwilm** [comment]
I'd like to get some more info about this crash. Would you mind running with this patch and providing the output starting with "pitch=" just before the panic? As I'm unable to repro, this would really help with putting together a proper fix.

```diff
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index c04057c..9f8fc3a 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -207,10 +207,13 @@ impl FreeTypeRasterizer {
         let buf = bitmap.buffer();
         let pitch = bitmap.pitch() as usize;
+        println!("pitch={}; rows={}; width={}; char={}", pitch, bitmap.rows(), bitmap.width(), c);
+
         let mut packed = Vec::with_capacity((bitmap.rows() * bitmap.width()) as usize);
         for i in 0..bitmap.rows() {
             let start = (i as usize) * pitch;
             let stop = start + bitmap.width() as usize;
+            println!("i={}; start={}; stop={}", i, start, stop);
             packed.extend_from_slice(&buf[start..stop]);
         }
```

**Comment by Somelauw** [comment]
```
pitch=0; rows=0; width=0; char=
pitch=1; rows=9; width=1; char=!
i=0; start=0; stop=1
i=1; start=1; stop=2
i=2; start=2; stop=3
i=3; start=3; stop=4
i=4; start=4; stop=5
i=5; start=5; stop=6
i=6; start=6; stop=7
i=7; start=7; stop=8
i=8; start=8; stop=9
pitch=1; rows=3; width=3; char="
i=0; start=0; stop=3
i=1; start=1; stop=4
thread 'main' panicked at 'index 4 out of range for slice of length 3', /checkout/src/libcore/slice.rs:578
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jwilm** [comment]
Wow, pitch < width is unexpected. Here's a slightly updated patch if you wouldn't mind :grin: 

```diff
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index c04057c..6a4ea06 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -207,10 +207,13 @@ impl FreeTypeRasterizer {
         let buf = bitmap.buffer();
         let pitch = bitmap.pitch() as usize;
+        println!("pitch={}; pitch_raw={}, rows={}; width={}; char={}", pitch, bitmap.pitch(), bitmap.rows(), bitmap.width(), c);
+
         let mut packed = Vec::with_capacity((bitmap.rows() * bitmap.width()) as usize);
         for i in 0..bitmap.rows() {
             let start = (i as usize) * pitch;
             let stop = start + bitmap.width() as usize;
+            println!("i={}; start={}; stop={}", i, start, stop);
             packed.extend_from_slice(&buf[start..stop]);
         }
```

**Comment by Somelauw** [comment]
```
pitch=0; pitch_raw=0, rows=0; width=0; char=
pitch=1; pitch_raw=1, rows=9; width=1; char=!
i=0; start=0; stop=1
i=1; start=1; stop=2
i=2; start=2; stop=3
i=3; start=3; stop=4
i=4; start=4; stop=5
i=5; start=5; stop=6
i=6; start=6; stop=7
i=7; start=7; stop=8
i=8; start=8; stop=9
pitch=1; pitch_raw=1, rows=3; width=3; char="
i=0; start=0; stop=3
i=1; start=1; stop=4
thread 'main' panicked at 'index 4 out of rangefor slice of length 3', /checkout/src/libcore/slice.rs:578
n
```

**Comment by hiberno** [comment]
I can confirm this issue running 32248471667dbdea33fca5e12fa0cb8a43482106 on Arch Linux. Setting font size to `11.0` prevents crashing. `10.0` crashes reproducibly. Changing the font used does not have any effect.

**Comment by jwilm** [comment]
Thanks @Somelauw for all the debugging.

I'm uncertain what to do at this point. Consider the log line:
```
pitch=1; pitch_raw=1, rows=3; width=3; char="
```
FreeType is telling us that the glyph data occupies 3 rows each with 3 bytes of glyph data (total 9 bytes). However, the pitch says that the buffer is only 1 byte per row (total 3 bytes). Naturally when we attempt to read all 9 bytes, we encounter an issue.

According to the FreeType docs, pitch should *always* be greater than or equal to width, but that's not what we see in this case.

I was considering inspecting the `freetype-rs` wrapper we are using to make sure it's not accidentally introducing an error.

Oh, I just realized we are a few versions behind on `freetype-rs`. Maybe one of you experiencing this error could run `cargo update -p freetype-rs`, rebuild, and see if the bug still occurs?

[FreeType docs]: https://www.freetype.org/freetype2/docs/glyphs/glyphs-7.html

**Comment by hiberno** [comment]
> Oh, I just realized we are a few versions behind on freetype-rs. Maybe one of you experiencing this error could run cargo update -p freetype-rs, rebuild, and see if the bug still occurs?

I tried, @jwilm. Alas, this does not change a thing. I updated `./font/Cargo.toml` to use `freetype-rs` version `0.13.0` and rebuilt Alacritty. This is what happend:

```sh
$ RUST_BACKTRACE=1 ./target/release/alacritty -v
Welcome to Alacritty.
device_pixel_ratio: 1
width: 1272, height: 1402
Initializing glyph cache
Finished initializing glyph cache in 0.049735936
set_inner_size: 640px × 384px
width: 644, height: 388
Cell Size: (8 x 16)
PTY Dimensions: Line(24) x Column(80)
width: 1272, height: 1402
width: 1272, height: 1402
thread 'main' panicked at 'index 56 out of range for slice of length 52', /checkout/src/libcore/slice.rs:578
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice.rs:578
   7: font::ft::FreeTypeRasterizer::get_rendered_glyph
             at /checkout/src/libcore/slice.rs:709
             at /checkout/src/libcore/slice.rs:560
             at ./font/src/ft/mod.rs:216
   8: font::ft::FreeTypeRasterizer::get_rendered_glyph
             at ./font/src/ft/mod.rs:193
   9: alacritty::renderer::GlyphCache::get
             at ./font/src/ft/mod.rs:84
             at /checkout/src/libstd/collections/hash/map.rs:1940
             at ./src/renderer/mod.rs:276
  10: alacritty::run
             at ./src/renderer/mod.rs:803
  11: alacritty::main
             at ./src/main.rs:64
  12: main
  13: __libc_start_main
  14: _start
```

I executed `echo 6KWe | base64 -d` in the thusly started Alacritty. This is with font size set to `10.0`, it does not crash with font size set to `11.0`. As before.

**Comment by jwilm** [comment]
@hiberno thank you very much for trying it out! Apparently we can't have an easy fix for this 🙃

**Comment by hiberno** [comment]
@jwilm You are very welcome! 

> Apparently we can't have an easy fix for this 🙃

In a year or four my eyes will be bad enough to force me to use font size `11.0` anyway :D

**Comment by carl-lucas** [comment]
@jwilm FYI this is the same error as #185 and #482 - I've posted some debug info on those issues. It's pitch < width screwing up that loop in mod.rs. Let me know if there is anything else I can do to help.

**Comment by m-wynn** [comment]
Partially out of boredom, I investigated more into the issue and created a test case that consistently gives me pitch<width in both rust and c++, so it's not the freetype-rs wrapper.  FontConfig is falling back to msgothic.ttc in this case, for me.

I don't know if this is helpful, but I have a filename in ~/Music which is panicking alacritty, and this bug is the last thing before I can use it daily.

[Here's](https://github.com/m-wynn/pitchwidthtest) the test case.  Sorry I'm neither great at rust or c++.

**Comment by jwilm** [comment]
Hey @m-wynn,

Thanks so much for the research you've done and for the test programs! Knowing that this was not a problem with the Rust bindings significantly narrowed down the problem space.

Using the test program/font you've provided, I've been able to put together a solution in #590. Would you mind taking it for a spin?

**Comment by m-wynn** [comment]
@jwilm Using the fix-glyph-panic branch, alacritty no longer panics!

**Comment by hiberno** [comment]
Thank you, @m-wynn, for debugging and thank you, @jwilm, for fixing this issue. It doesn't crash on me any longer. Awesome.

**Comment by dnsjts** [comment]
Also this solves the `cat`ting the `/dev/urandom` issue (#499), please confirm this.
Thank you for resolving this issue.

**Comment by hiberno** [comment]
@dnsjts It does not crash, though the terminal is rendered unusable (for me) afterwards: the font is all messed up.

**Comment by jwilm** [comment]
@hiberno can you post a screenshot?

**Comment by hiberno** [comment]
@jwilm Sorry, should've done that right away. What's even worse (or good, depends on how look at it): I cannot reproduce it. When I cancel `cat`-ing from `/dev/urandom` everything's fine again.
