### ISSUE TITLE
macOS: cannot switch input source, cannot use Pinyin

### ISSUE THREAD

**Issue by koterpillar** [jwilm/alacritty#748]
On macOS 10.12.6, with several input sources (System - Preferences - Input Sources) installed:

* Switching input sources using Ctrl-Cmd-Space doesn't work with Alacritty window focused.
* If I switch to a Russian input source _outside_ Alacritty, I can enter Russian characters inside Alacritty (good).
* If I switch to a Pinyin input source outside Alacritty, it gets ignored inside Alacritty (English characters appear unmodified instead).

Related: #44, possibly #209 and #61.

**Comment by mopp** [comment]
I have the same issue (?, is it issue or current spec ?).
I use google IME only.

* If I switch English mode, I can input well
* if I switch Japanese mode, it behaves English mode.

**Comment by BurningLutz** [comment]
Same issue.
Seems that input method is supported on linux but not on macOS.

**Comment by ryanp97** [comment]
Is this a planned feature for OSX? (I'd love input source support as well)

**Comment by Ch00k** [comment]
Same here. Love alacritty so far, but this issue is very annoying :(

**Comment by Ch00k** [comment]
According this the discussion in #945 this is not something that should be fixed in alacritty, but in winit/glutin :(

**Comment by Ch00k** [comment]
A workaround for this issue would be using Hammerspoon with this in `~/.hammerspoon/init.lua`:
```lua
local wf = hs.window.filter
wf_alacritty = wf.new{'Alacritty'}
wf_alacritty:subscribe(wf.windowFocused, function(window, title)
    hs.keycodes.setLayout('U.S.')
end)
```

**Comment by ryanp97** [comment]
@Ch00k Is it as simple as install/starting Hammerspoon after I add that snippet to `~/.hammerspoon/init.lua`?

**Comment by Ch00k** [comment]
@ryanp97 If you want alacritty to stick to one layout, then it is a simple as installing Hammerspoon and putting that snippet in `~/.hammerspoon/init.lua`, while replacing `U.S.` layout with the one you need.

**Comment by ryanp97** [comment]
@Ch00k Ah ok, and if I want it to switch on when I press some sequence of keys, I'm assuming I'll have to add some conditional statements to the snippet?

**Comment by Ch00k** [comment]
@ryanp97 There is a hammerspoon issue where the guy tries to achieve layout "stickiness" per window. Perhaps that can help. https://github.com/Hammerspoon/hammerspoon/issues/1314

**Comment by francesca64** [comment]
Could you try out this branch? https://github.com/francesca64/alacritty/tree/macos-kb

(Relevant winit PR: tomaka/winit#518)

**Comment by francesca64** [comment]
@ryanp97 I explained the situation with that here: https://github.com/jwilm/alacritty/issues/935#issuecomment-389254918

**Comment by chrisduerr** [comment]
Closing this issue because it seems like the main problem has been resolved. If you want to keep track of the other thing specifically, I don't think an issue for that exists yet and can probably be created.

@francesca64 do you know if something like the ctrl+shift+u for unicode in linux might be similar to the problem of combining characters on macos?

**Comment by francesca64** [comment]
@chrisduerr I don't entirely understand the question? (Also, if an issue is created for the other thing, be sure to ping me there.)

**Comment by francesca64** [comment]
Hm, that still doesn't work using the latest winit? I imagine that's done through the XIM protocol (via ibus/etc.), so I'd expect it to work.

**Comment by chrisduerr** [comment]
I thought it works through XIM too, that's why I was curious. I've tested it on your branch but no cigar.

There's an issue for this too: https://github.com/jwilm/alacritty/issues/866
